### ISSUE TITLE
Commiting all of our branches into the main branch

### ISSUE THREAD

**Issue by Rickie19999** [UniversityOfDundee-Computing/coursework-1---wikipedia-website-group-5-macintosh#4]
We have kind of done it, but to the ''Final concept'' branch, there are a few we still haven't done, but I'll be checking them out and commit it to the main one later on, once we finished the references

**Comment by viragszemann** [comment]
Alright, that's fine!

**Comment by Rickie19999** [comment]
All files are comited to branch, except the README, as it needs a bit of edits.

**Comment by Rickie19999** [comment]
Everything should be comitted
